runtime: python39  # Python version
entrypoint: gunicorn -b :$PORT main:app  # Adjust 'app:app' if your application instance is named differently

# Environment variables (only include if needed)
# env_variables:
#   SECRET_KEY: 'your-secret-key'
#   ANOTHER_VAR: 'another-value'

# Handlers for static files (only include if you have static content)
# handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: auto

# Instance class configuration (uncomment if you need to specify an instance class)
# instance_class: F1

# Automatic scaling configuration (uncomment if you want to configure scaling)
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 5
